version: "2"
services:
    examples:
        build: "./docker/examples"
        environment:
            APP_ENV: local
            APP_KEY: base64:kMvf1mHFIuCf+ZqMiId7yo6v4oKtjuWqnlxJTWsWv7k=
            LOG_LEVEL: debug
            BROADCAST_DRIVER: log
            CACHE_DRIVER: array
            QUEUE_CONNECTION: sync
            DB_CONNECTION: sqlite
            DB_DATABASE: ":memory:"
            APP_URL: http://127.0.0.1:9000
            MAIL_HOST: php
            MAIL_PORT: 1025
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: sender@site.com
            MAIL_FROM_NAME: sender
            RAY_HOST: php
            RAY_PORT: 8000
            VAR_DUMPER_SERVER: php:9912
            SENTRY_LARAVEL_DSN: http://sentry@php:8000/1
            LOG_SOCKET_URL: php:9913
            LOG_SLACK_WEBHOOK_URL: http://php:8000/slack
            INSPECTOR_URL: http://php:8000/inspector
            INSPECTOR_API_KEY: test
        ports:
            - 9000:8000
        depends_on:
            - php

    php:
        build: "./docker/server"
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
        ports:
            - 8000:8000
            - 1025:1025
            - 9912:9912
            - 9913:9913
        volumes:
            - ./:/app
        command: /bin/sh -c "touch database/database.sqlite && composer install && touch database/database.sqlite && php artisan db:wipe && php artisan cycle:schema:migrate && ./rr serve"
        depends_on:
            - db

    node:
        image: node:14-bullseye-slim
        volumes:
            - ./:/app:rw
        working_dir: /app
        command: bash -c "npm install && npm run watch"

    db:
        image: postgres
        environment:
            POSTGRES_USER: homestead
            POSTGRES_DB: homestead
            POSTGRES_PASSWORD: secret
        ports:
            - 5432:5432
